# Build using an explicit product image version. New versions are published on a monthly basis.
FROM sagcr.azurecr.io/webmethods-microservicesruntime:10.15

# Install the wpm tool. With webMethods 11, wpm will automatically be included and this step will no longer be needed
ADD --chown=sagadmin:sagadmin wpm /opt/softwareag/wpm
RUN chmod u+x /opt/softwareag/wpm/bin/wpm.sh
ENV PATH=/opt/softwareag/wpm/bin:$PATH

# Store the wpm token in an environment variable, so that we can use it in the subsequent steps
ARG WPM_TOKEN

# install the WmJDBCAdapter package using wpm - this is where the wpm token is used
WORKDIR /opt/softwareag/wpm
RUN /opt/softwareag/wpm/bin/wpm.sh install -ws https://packages.softwareag.com -wr softwareag -j $WPM_TOKEN -d /opt/softwareag/IntegrationServer WmJDBCAdapter
WORKDIR /